# -*- coding: utf-8 -*-
"""genePermutacionRecursivo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YGksQVtTOtUd9dcbwwV1PEEJUIUTh9S
"""

class GeneradorPermutaciones:
    """
    Clase que genera todas las permutaciones posibles de una lista usando recursión.
    """

    def __init__(self, lista):
        """
        Inicializa la lista para generar permutaciones.
        :param lista: list - Lista de elementos.
        """
        self.lista = lista

    def permutar(self, inicio=0):
        """
        Método recursivo que genera e imprime todas las permutaciones.
        :param inicio: int - Índice de inicio en la recursión.
        """
        if inicio == len(self.lista) - 1:
            print(self.lista)
        else:
            for i in range(inicio, len(self.lista)):
                # Intercambiar elementos
                self.lista[inicio], self.lista[i] = self.lista[i], self.lista[inicio]
                # Llamada recursiva
                self.permutar(inicio + 1)
                # Deshacer intercambio (backtracking)
                self.lista[inicio], self.lista[i] = self.lista[i], self.lista[inicio]

    def mostrar_permutaciones(self):
        """
        Inicia la generación de permutaciones e imprime los resultados.
        """
        print(f"\nPermutaciones posibles de la lista {self.lista}:\n")
        self.permutar()
        print("\n==============================\n")


# ============================================
# EJECUCIÓN DEL PROGRAMA
# ============================================
if __name__ == "__main__":
    print("=== Generador de Permutaciones Recursivo ===")
    try:
        elementos = input("Ingrese los elementos de la lista separados por espacio: ")
        lista = elementos.split()
        if not lista:
            print("❌ Error: la lista no puede estar vacía.")
        else:
            generador = GeneradorPermutaciones(lista)
            generador.mostrar_permutaciones()
    except Exception as e:
        print("❌ Error:", e)